language: php
dist: trusty

php:
  - 7.1
  - 7.2

before_script:
  - composer install --no-interaction

code_climate:
  repo_token: $CODECLIMATE_REPO_TOKEN

script:
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
  - vendor/bin/test-reporter

notifications:
  email:
      recipients:
        - contact@anthonygrimes.co.uk
      on_success: never
      on_failure: always